### ISSUE TITLE
SQLite3 platform needs some more configuration to pass more tests.

### ISSUE THREAD

**Issue by tblanchard** [pharo-rdbms/glorp#34]
A number of tests are fixed by defining method maximumQueryValueSize and returning 50000.

This is the largest string SQLite can handle in a like or glob expression and, lets be real, one isn't likely to be querying with parameters this large.  

See https://sqlite.org/limits.html

"The pattern matching algorithm used in the default LIKE and GLOB implementation of SQLite can exhibit O(N²) performance (where N is the number of characters in the pattern) for certain pathological cases. To avoid denial-of-service attacks from miscreants who are able to specify their own LIKE or GLOB patterns, the length of the LIKE or GLOB pattern is limited to SQLITE_MAX_LIKE_PATTERN_LENGTH bytes. The default value of this limit is 50000. A modern workstation can evaluate even a pathological LIKE or GLOB pattern of 50000 bytes relatively quickly. The denial of service problem only comes into play when the pattern length gets into millions of bytes. Nevertheless, since most useful LIKE or GLOB patterns are at most a few dozen bytes in length, paranoid application developers may want to reduce this parameter to something in the range of a few hundred if they know that external users are able to generate arbitrary patterns."

Also need to define autoTrimsStringsLongerThanColumnSize to return true.  It doesn't really trim strings.  SQLite will let you put a string of arbitrary length in any field type and it does not constrain inputs like other dbs.  But the tests use this to determine whether to expect an error to be thrown if an oversized string is set.  SQLite does not throw an error, it takes whatever you give it.

Finally, I went ahead and defined sqlTextCurrentServerUTCTimestamp because despite not having date and time types (use strings), it does have functions for manipulating date and time types, but always returns formatted strings.

**Comment by PierceNg** [comment]
@tblanchard Can you try with ```UDBCSQLite3Platform``` instead of ```SQLite3Platform```? The latter is from Glorp upstream. When I did the initial integration of Glorp and SQLite on Pharo 5, I created ```UDBCSQLite3Platform``` subclassing ```SQLite3Platform```, the intention of which was to make all necessary changes in this class and leave Glorp upstream code untouched as much as possible. My SQLite-related changes and tests have always been for ```UDBCSQLite3Platform```.

**Comment by tblanchard** [comment]
@PierceNg a user of this package would know this how?  I ran the tests with SQLite3Platform because I have no idea at all what UDBCSQLitePlatform is for and it doesn't say anywhere.  I thought it was a garage holdover or something and I spent the better part of a day and a half diagnosing and fixing failures with SQLite3Platform.

**Comment by PierceNg** [comment]
On Fri, Feb 05, 2021 at 09:52:03AM -0800, Todd Blanchard wrote:
> @PierceNg a user of this package would know this how?  

By searching the web, by asking on mailing lists, and so on?  Most search
engine hits would point to my blog or my repos.

The Metacello loading snippet for loading Glorp + SQLite has been in place
since 2018:

  https://www.samadhiweb.com/blog/2018.10.23.glorp.sqlite3.html

I just tested with a fresh Pharo 7.0.5 image with the snippet stated in the
README of https://github.com/pharo-rdbms/glorp-sqlite3:

```
Metacello new 
    repository: 'github://pharo-rdbms/glorp-sqlite3:p7_newsqlite';
    baseline: 'GlorpSQLite';
    load.
```

890 run, 890 test passes, 13 skipped. One more skipped compared to my 2018
blog post, because (IIRC) the then-new SQLite binding broke part of one
blob test.

**Comment by tblanchard** [comment]
I shouldn't have to search the web and ask on mailing lists about a package.  It should be documented in the package.  The UDBCSQLitePlatform class comment is pretty unhelpful in that regard.  That's where I looked.

I'm working on Pharo-SQLite3 and trying to make that work out of the box.  That seems to be what people hop on when they want SQLite, optionally with glorp. 

It seems there is a duplication of effort here.  I would like us to have packages of Pharo-<databasename> with optional glorp loading targets so someone can run a load command and get going.  I'm open to proposals to get to one clean package.

Also, with regard to glorp updates, who pulls those?  What is the process for getting updates?  I kind of figured the fork was a one time thing and we carry it forward.  Is there a process to push enhancements back?  Because the SQLitePlatform is half baked at best.
